/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export interface UmaCharacter {
  birthDay: number
  birthMonth: number
  categoryLabel: string
  categoryLabelEn: string
  categoryValue: string
  colorMain: string
  colorSub: string
  dateGmt: string
  detailImgPc: string
  detailImgSp: string
  earsFact: string
  familyFact: string
  gameId: number
  grade: string
  height: number
  id: number
  link: string
  modifiedGmt: string
  nameEn: string
  nameEnInternal: string
  nameJp: string
  preferredUrl: string
  profile: string
  residence: string
  rowNumber: number
  shoeSize: string
  siteIdx: number
  sizeB: number
  sizeH: number
  sizeW: number
  slogan: string
  snsHeader: string
  snsIcon: string
  strengths: string
  tailFact: string
  thumbImg: string
  voice: string
  weaknesses: string
  weight: string
}

export declare function umaFetch(id: number): Promise<string>
